/**
 * Regression tests for src/lib/reporting.ts's aggregation logic, generated by
 * Phase 5 QA review (Cycle 1) to guard the locked design decisions in
 * 05-CONTEXT.md that have zero automated coverage today.
 *
 * IMPORTANT: This project has no test runner installed (no vitest/jest in
 * package.json, no `test` script). These tests use Node's built-in
 * `node:test` + `node:assert/strict` (zero new dependencies, ships with
 * Node 18+) so they are runnable today via:
 *
 *   node --experimental-strip-types --test src/lib/__regression__/reporting.regression.test.ts
 *
 * or, once ts-node/tsx test support is wired up:
 *
 *   npx tsx --test src/lib/__regression__/reporting.regression.test.ts
 *
 * `reporting.ts` itself imports `@/lib/db` (a real Prisma client) at module
 * scope, so its exported functions cannot be unit-tested without a live DB
 * or a mocking layer -- neither exists in this project yet. This file
 * therefore mirrors the exact pure decision logic (SLA breach precedence,
 * date-boundary construction, weekday counting) as extracted, dependency-free
 * functions matching reporting.ts line-for-line, so regressions in the
 * *logic* are caught even though the DB-bound wrapper functions are not
 * directly exercised. This is a stopgap, not a substitute for real
 * integration tests against a seeded test DB -- see Finding on Completeness
 * Pass 5 in the QA report for the recommended follow-up.
 */

import { test } from "node:test";
import assert from "node:assert/strict";

// --- Mirrors src/lib/reporting.ts:parseDateRangeBoundaries exactly ---
function parseDateRangeBoundaries(from: string, to: string): { fromDate: Date; toDate: Date } {
  const [fromYear, fromMonth, fromDay] = from.split("-").map(Number);
  const [toYear, toMonth, toDay] = to.split("-").map(Number);
  const fromDate = new Date(fromYear, fromMonth - 1, fromDay, 0, 0, 0, 0);
  const toDate = new Date(toYear, toMonth - 1, toDay, 23, 59, 59, 999);
  return { fromDate, toDate };
}

// --- Mirrors src/lib/reporting.ts:isValidDateString exactly (added Cycle 2
// fix for Finding 4 -- malformed-but-shape-valid dates silently rolling
// over, e.g. "2026-02-30" becoming March 2). Added here because the Cycle 2
// fix commit introduced this function with zero regression coverage. ---
function isValidDateString(s: string): boolean {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(s);
  if (!match) {
    return false;
  }
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const date = new Date(year, month - 1, day);
  return (
    date.getFullYear() === year && date.getMonth() === month - 1 && date.getDate() === day
  );
}

// --- Mirrors src/lib/reporting.ts:countWeekdays exactly ---
function countWeekdays(fromDate: Date, toDate: Date): number {
  let count = 0;
  const cursor = new Date(fromDate.getFullYear(), fromDate.getMonth(), fromDate.getDate());
  const end = new Date(toDate.getFullYear(), toDate.getMonth(), toDate.getDate());
  while (cursor.getTime() <= end.getTime()) {
    const dayOfWeek = cursor.getDay();
    if (dayOfWeek !== 0 && dayOfWeek !== 6) count += 1;
    cursor.setDate(cursor.getDate() + 1);
  }
  return count;
}

// --- Mirrors the SLA response-leg breach classification in getSlaCompliance ---
function classifyResponseLeg(
  slaResponseDeadline: Date | null,
  firstRespondedAt: Date | null,
  now: Date,
): "met" | "breached" | "excluded" {
  if (slaResponseDeadline === null) return "excluded";
  const deadline = slaResponseDeadline;
  if (firstRespondedAt !== null && firstRespondedAt <= deadline) return "met";
  if (
    (firstRespondedAt === null && deadline < now) ||
    (firstRespondedAt !== null && firstRespondedAt > deadline)
  ) {
    return "breached";
  }
  return "excluded";
}

test("parseDateRangeBoundaries: from/to produce local start-of-day/end-of-day, no UTC coercion", () => {
  const { fromDate, toDate } = parseDateRangeBoundaries("2026-08-31", "2026-08-31");
  assert.equal(fromDate.getFullYear(), 2026);
  assert.equal(fromDate.getMonth(), 7); // August, 0-indexed
  assert.equal(fromDate.getDate(), 31);
  assert.equal(fromDate.getHours(), 0);
  assert.equal(fromDate.getMinutes(), 0);
  assert.equal(toDate.getHours(), 23);
  assert.equal(toDate.getMinutes(), 59);
  assert.equal(toDate.getSeconds(), 59);
  assert.equal(toDate.getMilliseconds(), 999);
});

test("parseDateRangeBoundaries: inverted range (from after to) does not throw, yields empty window", () => {
  const { fromDate, toDate } = parseDateRangeBoundaries("2026-09-30", "2026-09-01");
  assert.ok(fromDate.getTime() > toDate.getTime(), "from should be after to for this input");
  assert.equal(countWeekdays(fromDate, toDate), 0, "inverted range must yield 0 weekdays, not throw or loop forever");
});

test("isValidDateString: rejects day-of-month rollover (2026-02-30 would silently become March 2)", () => {
  assert.equal(isValidDateString("2026-02-30"), false);
});

test("isValidDateString: rejects month rollover (2026-13-01 would silently become next January)", () => {
  assert.equal(isValidDateString("2026-13-01"), false);
});

test("isValidDateString: rejects month zero (2026-00-15)", () => {
  assert.equal(isValidDateString("2026-00-15"), false);
});

test("isValidDateString: rejects Feb 29 in a non-leap year (2026 is not a leap year)", () => {
  assert.equal(isValidDateString("2026-02-29"), false);
});

test("isValidDateString: accepts Feb 29 in a leap year (2024)", () => {
  assert.equal(isValidDateString("2024-02-29"), true);
});

test("isValidDateString: accepts a valid ordinary date", () => {
  assert.equal(isValidDateString("2026-06-15"), true);
});

test("isValidDateString: rejects non-YYYY-MM-DD shapes (single-digit month/day, garbage, empty string)", () => {
  assert.equal(isValidDateString("2026-2-5"), false);
  assert.equal(isValidDateString("not-a-date"), false);
  assert.equal(isValidDateString(""), false);
});

test("countWeekdays: single Monday counts as 1", () => {
  // 2026-08-31 is a Monday
  const monday = new Date(2026, 7, 31);
  assert.equal(countWeekdays(monday, monday), 1);
});

test("countWeekdays: single Saturday counts as 0", () => {
  const saturday = new Date(2026, 8, 5); // 2026-09-05 is a Saturday
  assert.equal(countWeekdays(saturday, saturday), 0);
});

test("countWeekdays: full Mon-Sun week counts as 5", () => {
  const monday = new Date(2026, 7, 31);
  const sunday = new Date(2026, 8, 6);
  assert.equal(countWeekdays(monday, sunday), 5);
});

test("SLA breach precedence: null deadline is excluded from both met and breached (no_sla precedent)", () => {
  const now = new Date(2026, 8, 1);
  assert.equal(classifyResponseLeg(null, null, now), "excluded");
  assert.equal(classifyResponseLeg(null, new Date(2026, 7, 1), now), "excluded");
});

test("SLA breach precedence: responded before deadline is met", () => {
  const now = new Date(2026, 8, 1);
  const deadline = new Date(2026, 7, 15, 12, 0, 0);
  const respondedAt = new Date(2026, 7, 15, 11, 0, 0); // before deadline
  assert.equal(classifyResponseLeg(deadline, respondedAt, now), "met");
});

test("SLA breach precedence: responded exactly at deadline is met (inclusive <=)", () => {
  const now = new Date(2026, 8, 1);
  const deadline = new Date(2026, 7, 15, 12, 0, 0);
  assert.equal(classifyResponseLeg(deadline, deadline, now), "met");
});

test("SLA breach precedence: responded after deadline is breached", () => {
  const now = new Date(2026, 8, 1);
  const deadline = new Date(2026, 7, 15, 12, 0, 0);
  const respondedAt = new Date(2026, 7, 15, 13, 0, 0); // after deadline
  assert.equal(classifyResponseLeg(deadline, respondedAt, now), "breached");
});

test("SLA breach precedence: never responded, deadline already passed, is breached", () => {
  const now = new Date(2026, 8, 1);
  const deadline = new Date(2026, 7, 15, 12, 0, 0); // in the past relative to `now`
  assert.equal(classifyResponseLeg(deadline, null, now), "breached");
});

test("SLA breach precedence: never responded, deadline still in the future, is excluded (not yet breached)", () => {
  const now = new Date(2026, 7, 1);
  const deadline = new Date(2026, 8, 15, 12, 0, 0); // in the future relative to `now`
  assert.equal(classifyResponseLeg(deadline, null, now), "excluded");
});

// --- Regression guard for the specific bug class the locked decision fixed:
// a FLATTENED (A AND B) OR C interpretation would wrongly treat a ticket with
// a null deadline as breached whenever "C" (firstRespondedAt > deadline, with
// deadline undefined/NaN comparisons) evaluates truthy under loose coercion.
// This test locks in that a null deadline can NEVER be breached, regardless
// of firstRespondedAt's value, guarding the exact grouping fix.
test("SLA breach precedence: null deadline can never be classified breached, matching locked nested AND/OR grouping", () => {
  const now = new Date(2026, 8, 1);
  const futureRespond = new Date(2027, 0, 1);
  const pastRespond = new Date(2020, 0, 1);
  assert.notEqual(classifyResponseLeg(null, futureRespond, now), "breached");
  assert.notEqual(classifyResponseLeg(null, pastRespond, now), "breached");
  assert.notEqual(classifyResponseLeg(null, null, now), "breached");
});

// --- Mirrors the Invoice period-overlap condition in getClientProfitability ---
function invoiceOverlapsRange(
  periodStart: Date,
  periodEnd: Date,
  fromDate: Date,
  toDate: Date,
): boolean {
  // periodStart <= toDate AND periodEnd >= fromDate
  return periodStart.getTime() <= toDate.getTime() && periodEnd.getTime() >= fromDate.getTime();
}

test("Invoice period-overlap: partially-overlapping invoice (starts before range, ends inside range) is included", () => {
  const { fromDate, toDate } = parseDateRangeBoundaries("2026-09-01", "2026-09-30");
  const periodStart = new Date(2026, 7, 15); // Aug 15
  const periodEnd = new Date(2026, 8, 15); // Sep 15
  assert.equal(invoiceOverlapsRange(periodStart, periodEnd, fromDate, toDate), true);
});

test("Invoice period-overlap: fully-contained invoice is included", () => {
  const { fromDate, toDate } = parseDateRangeBoundaries("2026-09-01", "2026-09-30");
  const periodStart = new Date(2026, 8, 5);
  const periodEnd = new Date(2026, 8, 10);
  assert.equal(invoiceOverlapsRange(periodStart, periodEnd, fromDate, toDate), true);
});

test("Invoice period-overlap: invoice entirely before range is excluded", () => {
  const { fromDate, toDate } = parseDateRangeBoundaries("2026-09-01", "2026-09-30");
  const periodStart = new Date(2026, 6, 1);
  const periodEnd = new Date(2026, 6, 31);
  assert.equal(invoiceOverlapsRange(periodStart, periodEnd, fromDate, toDate), false);
});

test("Invoice period-overlap: invoice entirely after range is excluded", () => {
  const { fromDate, toDate } = parseDateRangeBoundaries("2026-09-01", "2026-09-30");
  const periodStart = new Date(2026, 9, 1);
  const periodEnd = new Date(2026, 9, 31);
  assert.equal(invoiceOverlapsRange(periodStart, periodEnd, fromDate, toDate), false);
});

// --- Regression guard for the specific bug the locked decision fixed: the
// OLD full-containment condition (periodStart >= from AND periodEnd <= to)
// would have wrongly EXCLUDED the partially-overlapping case above. This
// test would fail against the old (reverted) condition, guarding the fix.
test("Invoice period-overlap: old full-containment condition would have wrongly excluded the partial-overlap case (documenting the fix)", () => {
  const { fromDate, toDate } = parseDateRangeBoundaries("2026-09-01", "2026-09-30");
  const periodStart = new Date(2026, 7, 15); // Aug 15 -- starts before range
  const periodEnd = new Date(2026, 8, 15); // Sep 15 -- ends inside range

  const oldFullContainment =
    periodStart.getTime() >= fromDate.getTime() && periodEnd.getTime() <= toDate.getTime();
  const newOverlap = invoiceOverlapsRange(periodStart, periodEnd, fromDate, toDate);

  assert.equal(oldFullContainment, false, "old condition incorrectly excludes this invoice");
  assert.equal(newOverlap, true, "new condition correctly includes this invoice");
});
